use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};

pub fn generate_android_project(base: &str) {
    let root = format!("{}/android", base);

    let dirs = [
        "app",
        "app/src",
        "app/src/main",
        "app/src/main/java/com/amethyst/demo",
        "app/src/main/res/values",
    ];

    for dir in dirs {
        fs::create_dir_all(format!("{}/{}", root, dir)).expect("dir create failed");
    }

    write(
        &format!("{}/README.md", root),
        "Amethyst Android demo generated by Forge\n",
    );

    write(
        &format!("{}/app/src/main/AndroidManifest.xml", root),
        r#"<manifest package="com.amethyst.demo">
  <application android:label="Amethyst Demo">
    <activity android:name=".MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
  </application>
</manifest>
"#,
    );

    write(
        &format!("{}/app/src/main/java/com/amethyst/demo/MainActivity.java", root),
        r#"package com.amethyst.demo;

import android.app.Activity;
import android.os.Bundle;

public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }
}
"#,
    );

    write(
        &format!("{}/app/src/main/res/values/strings.xml", root),
        r#"<resources>
  <string name="app_name">Amethyst Demo</string>
</resources>
"#,
    );
}

/// Deterministic hash of a generated project directory.
/// - Recurses files
/// - Sorts paths for stability
/// - Hashes: (relative_path + 0x00 + file_bytes) for each file in order
pub fn hash_project_dir(project_root: &str) -> String {
    let root = Path::new(project_root);
    let mut files: Vec<PathBuf> = Vec::new();
    collect_files(root, root, &mut files);

    files.sort_by(|a, b| a.to_string_lossy().cmp(&b.to_string_lossy()));

    let mut hasher = Sha256::new();

    for path in files {
        let rel = path.strip_prefix(root).unwrap_or(&path);
        let rel_s = rel.to_string_lossy().replace('\\', "/");

        hasher.update(rel_s.as_bytes());
        hasher.update([0u8]); // separator

        let bytes = fs::read(&path).expect("read file failed");
        hasher.update(bytes);
        hasher.update([0u8]); // separator
    }

    let digest = hasher.finalize();
    hex_lower(&digest)
}

fn collect_files(root: &Path, cur: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(cur) {
        Ok(e) => e,
        Err(_) => return,
    };

    for entry in entries.flatten() {
        let p = entry.path();
        if p.is_dir() {
            // skip build artefacts if any
            if p.file_name().map(|s| s == "target").unwrap_or(false) {
                continue;
            }
            collect_files(root, &p, out);
        } else if p.is_file() {
            out.push(p);
        }
    }
}

fn hex_lower(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut s = String::with_capacity(bytes.len() * 2);
    for &b in bytes {
        s.push(HEX[(b >> 4) as usize] as char);
        s.push(HEX[(b & 0x0f) as usize] as char);
    }
    s
}

fn write(path: &str, contents: &str) {
    fs::write(Path::new(path), contents).expect("write failed");
}
