use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

pub fn generate_android_project(base: &str) -> (String, String) {
    let root = format!("{}/android", base);

    let dirs = [
        "app",
        "app/src",
        "app/src/main",
        "app/src/main/java/com/amethyst/demo",
        "app/src/main/res",
        "app/src/main/res/values",
    ];

    for dir in dirs {
        fs::create_dir_all(format!("{}/{}", root, dir)).expect("dir create failed");
    }

    write_file(
        &format!("{}/README.md", root),
        "Amethyst Android demo generated by Forge\n",
    );

    write_file(
        &format!("{}/app/src/main/AndroidManifest.xml", root),
        r#"<manifest package="com.amethyst.demo">
  <application android:label="Amethyst Demo">
    <activity android:name=".MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
  </application>
</manifest>
"#,
    );

    write_file(
        &format!("{}/app/src/main/java/com/amethyst/demo/MainActivity.java", root),
        r#"package com.amethyst.demo;

import android.app.Activity;
import android.os.Bundle;

public class MainActivity extends Activity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
  }
}
"#,
    );

    write_file(
        &format!("{}/app/src/main/res/values/strings.xml", root),
        r#"<resources>
  <string name="app_name">Amethyst Demo</string>
</resources>
"#,
    );

    // Build deterministic manifest + root hash
    let (manifest_json, root_hash_hex) = build_manifest_and_root_hash(&PathBuf::from(&root));
    write_file(&format!("{}/manifest.json", root), &manifest_json);

    (root, root_hash_hex)
}

fn write_file(path: &str, contents: &str) {
    fs::write(Path::new(path), contents).expect("write failed");
}

fn build_manifest_and_root_hash(root: &Path) -> (String, String) {
    let mut files: Vec<PathBuf> = Vec::new();
    collect_files(root, root, &mut files);

    // Sort for determinism
    files.sort_by(|a, b| a.to_string_lossy().cmp(&b.to_string_lossy()));

    let mut entries_json = String::new();
    entries_json.push('[');

    for (i, abs) in files.iter().enumerate() {
        let rel = abs.strip_prefix(root).unwrap().to_string_lossy().to_string();
        let bytes = fs::read(abs).expect("read failed");
        let file_hash = sha256_hex(&bytes);

        if i > 0 {
            entries_json.push(',');
        }
        entries_json.push_str(&format!(
            r#"{{"path":"{}","sha256":"{}","bytes":{}}}"#,
            escape_json(&rel),
            file_hash,
            bytes.len()
        ));
    }

    entries_json.push(']');

    let manifest = format!(r#"{{"root":"{}","files":{}}}"#, escape_json(&root.to_string_lossy()), entries_json);

    let root_hash = sha256_hex(manifest.as_bytes());
    (manifest, root_hash)
}

fn collect_files(root: &Path, dir: &Path, out: &mut Vec<PathBuf>) {
    let mut entries: Vec<_> = fs::read_dir(dir).expect("read_dir failed").collect::<Result<_, _>>().unwrap();
    entries.sort_by(|a, b| a.path().to_string_lossy().cmp(&b.path().to_string_lossy()));

    for e in entries {
        let p = e.path();
        if p.is_dir() {
            collect_files(root, &p, out);
        } else if p.is_file() {
            out.push(p);
        }
    }
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(bytes);
    let digest = h.finalize();
    hex::encode(digest)
}

fn escape_json(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
