use std::fs;
use std::io;
use std::path::Path;

pub fn generate_amethyst_demo() -> Result<(), io::Error> {
    let base = Path::new("generated/amethyst-demo");

    // Create base directories
    fs::create_dir_all(base.join("android"))?;

    // Write README
    fs::write(
        base.join("README.md"),
        "# Amethyst Demo\n\nGenerated by FORGE via Pilgrim Core.\n",
    )?;

    Ok(())
}
